update

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -78,22 +78,22 @@ jobs:
       - uses: actions/checkout@v2
       - name: Install dependencies
         run: npm install
-      # - name: Test
-      #   run: npm run test-jenkins
       - name: Test
-        uses: mattallty/jest-github-action@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          test-command: "npm run coverage-jenkins" 
-      - uses: actions/upload-artifact@v2
-        if: success() || failure() 
-        with:
-          name: test-results 
-          path: ./coverage/test.results.xml
-      - name: Save Code Linting Report JSON
-        run: npm run lint:json
-        continue-on-error: true 
+        run: npm run test-jenkins
+      # - name: Test
+      #   uses: mattallty/jest-github-action@v1
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   with:
+      #     test-command: "npm run coverage-jenkins" 
+      # - uses: actions/upload-artifact@v2
+      #   if: success() || failure() 
+      #   with:
+      #     name: test-results 
+      #     path: ./coverage/test.results.xml
+      # - name: Save Code Linting Report JSON
+      #   run: npm run lint:json
+      #   continue-on-error: true 
       - name: Annotate Code Linting Results
         uses: ataylorme/eslint-annotate-action@1.2.0
         with:
